### PR TITLE
NanEncode: fix argument type for node::Encode

### LINKED ISSUE #272: ../node_modules/nan/nan.h:1848:10: error: no matching function for call to 'Encode'
Just got this:

```
In file included from ../src/prf.cc:2:
../node_modules/nan/nan.h:1848:10: error: no matching function for call to 'Encode'
  return node::Encode(
         ^~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by indutny**
`node::Encode` expects `const char *`, not `const void *`.

Fix #272

### CODE REVIEW

**Comment by ide** [comment]
Fixes #267 too (same issue)

**Comment by indutny** [comment]
cc @rvagg @kkoopa

**Comment by kkoopa** [comment]
It is more complicated than this. #265 has more information. It boils down to needing special case handling of UCS2 encoding while keeping the API consistent.

**Comment by indutny** [comment]
@kkoopa looks better now?

**Comment by indutny** [comment]
Oopps made a mistake. Force-pushing in a bit.

**Comment by indutny** [comment]
@kkoopa Done

**Comment by kkoopa** [comment]
Yes, this is much better. Don't see anything objectionable. Will see what test outcome is.

**Comment by indutny** [comment]
@kkoopa either AppVeyor hang, or has very long queue...

**Comment by kkoopa** [comment]
It usually has a very long queue.

File: nan.h [hunk 1]
```diff
@@ -1845,10 +1845,21 @@ namespace Nan {
...
-    , buf, len
-    , static_cast<node::encoding>(encoding));
+  v8::Isolate* isolate = v8::Isolate::GetCurrent();
+  node::encoding node_enc = static_cast<node::encoding>(encoding);
+
+  if (encoding == Nan::UCS2) {
+    return node::Encode(
+        isolate
+      , reinterpret_cast<const uint16_t *>(buf)
+      , len);
```
Comment (kkoopa) [inline nan.h]: This will not work properly on joyent/node 0.11.16, it will encode with the default encoding=node::BINARY. It is currently only io.js that has broken out UCS 2 handling.

**Comment by kkoopa** [comment]
Can you add unit tests as well? With all the implicit arguments, this might actually compile even if it produces the wrong output.

**Comment by indutny** [comment]
Not at the moment, busy with other stuff right now. Maybe tomorrow?

**Comment by kkoopa** [comment]
Sure, it can wait until then.

**Comment by indutny** [comment]
@kkoopa please review ;)

**Comment by kkoopa** [comment]
Tests look good, but don't seem to pass at the moment. Also, you should still condition on NODE_MODULE_VERSION being >= 42 before calling `node::Encode(Isolate *, const uint16_t *, size_t)`. In earlier versions of the 0.11 series (e.g. joyent/node 0.11.16), that will resolve to `node::Encode(Isolate *, const uint16_t *, size_t, node::encoding = BINARY)` because the three-argument node::Encode does not exist.

**Comment by kkoopa** [comment]
Tests look good, but don't seem to pass at the moment. Also, you should still condition on NODE_MODULE_VERSION being >= 42 before calling `node::Encode(Isolate *, const uint16_t *, size_t)`. In earlier versions of the 0.11 series (e.g. joyent/node 0.11.16), that will resolve to `node::Encode(Isolate *, const uint16_t *, size_t, node::encoding = BINARY)` because the three-argument node::Encode does not exist.

**Comment by indutny** [comment]
Gosh, node.js 0.8 does not support HEX encoding. @kkoopa how much do we care about it? Should I polyfill it?

**Comment by kkoopa** [comment]
Preferrably, yes. The API should be consistent across versions.

**Comment by indutny** [comment]
@kkoopa there is another thing. It does not support any encoding except binary :) I guess I'll just put the node-v0.10 encoding function in.

**Comment by Globegitter** [comment]
Is this PR supposed to supersede https://github.com/rvagg/nan/pull/265 or are these achieving slightly different things?
I am trying to build `node-sass` on iojs and getting it to work with https://github.com/rvagg/nan/pull/265 but not with this PR.

**Comment by kkoopa** [comment]
It does not? How can I have missed that in the first place? How annoying.

**Comment by indutny** [comment]
@kkoopa I'm porting string_bytes.h to nan.

**Comment by kkoopa** [comment]
Alright, I guess it had to happen sooner or later. I've been putting it off for 
too long. Parts might have to be in a class, as you probably want some of it 
to be static methods. Switches and such don't inline too well. The good thing 
is that existing code can be cleaned up if it does not have to contain 
workarounds for missing parts of the string conversion routines.

**Comment by indutny** [comment]
@kkoopa I hope this commit will do the job :)

**Comment by indutny** [comment]
@kkoopa yay, travis is happy with it.

**Comment by kkoopa** [comment]
Wonderful. I assume you have tested on io.js too, so that's all good. One final thing, now that you backported string_bytes.h, it might not be necessary to have the special BUFFER encoding handling
in `# if  (NODE_MODULE_VERSION < 0x000B)`. Removing it would clean up and simplify the code a little.

**Comment by indutny** [comment]
@kkoopa does 0x000B means node.js v0.10? and < 0x000B means 0.8?

**Comment by kkoopa** [comment]
Yes, that should be it. Had that special case because 0.8 did not support BUFFER encoding, but it was handled almost same way as BINARY.

**Comment by indutny** [comment]
Ok, force pushed!

**Comment by kkoopa** [comment]
Seems to work, indeed. Many thanks.

**Comment by indutny** [comment]
You are welcome! Please release ;)

**Comment by reqshark** [comment]
fixes `ws`
